version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: minifeed:latest  # Name of the image you want to build
    ports:
      - "5010:5000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
